imports:
  - { resource: actions/* }
  - { resource: voters/* }

services:
    user_listener:
        class: AppBundle\EventListener\UserListener
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.orm.entity_listener }

    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }


    app.service.update_token_sender:
        class: AppBundle\Service\UpdateTokenSender\UpdateTokenSender
        public: true
        arguments: ["@requestum_email_sender", "%env(DEFAULT_EMAIL_FROM)%", "%env(UPDATE_TOKEN_LINKS)%"]

